version: "3.8"

services:
  fastapi:
    image: fastapi
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: unless-stopped
